### ISSUE TITLE
location map with bounding box missing in UI

### ISSUE THREAD

**Issue by smrgeoinfo** [ngds/ckanext-ngds-bku03232018#633]
Its in the out of the box build (e.g. http://catalog.data.gov/dataset/arizona-aqueous-spring-chemistry); we need it back

**Comment by GaryHudmanAZGS** [comment]
Configured back in for the dataset view with basic read capability, and for search tools.  The editor functions, however, where the extent can be drawn and populate the coordinate fields, does not seem to exist out of the box.  I can build a custom one, do you want this ? 
Gary

**Comment by smrgeoinfo** [comment]
fixed (a month ago!)
